ALTER TABLE [Projects] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [Projects] DISABLE TRIGGER ALL
GO

SET IDENTITY_INSERT [Projects] ON 
PRINT 'Begin inserting data in Projects'
SET IDENTITY_INSERT [Projects] OFF 
ALTER TABLE [Projects] CHECK CONSTRAINT ALL
GO

ALTER TABLE [Projects] ENABLE TRIGGER ALL
GO



ALTER TABLE [Users] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [Users] DISABLE TRIGGER ALL
GO

SET IDENTITY_INSERT [Users] ON 
PRINT 'Begin inserting data in Users'
INSERT INTO [Users] ([ID], [Username], [Role], [Enabled], [Password])
VALUES(485, 'admin', 3, 1, '3DA541559918A808C2402BBA5012F6C60B27661C')
SET IDENTITY_INSERT [Users] OFF 
ALTER TABLE [Users] CHECK CONSTRAINT ALL
GO

ALTER TABLE [Users] ENABLE TRIGGER ALL
GO



ALTER TABLE [Modules] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [Modules] DISABLE TRIGGER ALL
GO

SET IDENTITY_INSERT [Modules] ON 
PRINT 'Begin inserting data in Modules'
SET IDENTITY_INSERT [Modules] OFF 
ALTER TABLE [Modules] CHECK CONSTRAINT ALL
GO

ALTER TABLE [Modules] ENABLE TRIGGER ALL
GO



ALTER TABLE [TaskAssignments] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [TaskAssignments] DISABLE TRIGGER ALL
GO

PRINT 'Begin inserting data in TaskAssignments'
ALTER TABLE [TaskAssignments] CHECK CONSTRAINT ALL
GO

ALTER TABLE [TaskAssignments] ENABLE TRIGGER ALL
GO



ALTER TABLE [Tasks] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [Tasks] DISABLE TRIGGER ALL
GO

SET IDENTITY_INSERT [Tasks] ON 
PRINT 'Begin inserting data in Tasks'
SET IDENTITY_INSERT [Tasks] OFF 
ALTER TABLE [Tasks] CHECK CONSTRAINT ALL
GO

ALTER TABLE [Tasks] ENABLE TRIGGER ALL
GO



ALTER TABLE [UserProfile] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [UserProfile] DISABLE TRIGGER ALL
GO

PRINT 'Begin inserting data in UserProfile'
INSERT INTO [UserProfile] ([ID], [FirstName], [LastName], [Address], [City], [State], [Zip], [PhoneNumber], [Email])
VALUES(485, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ALTER TABLE [UserProfile] CHECK CONSTRAINT ALL
GO

ALTER TABLE [UserProfile] ENABLE TRIGGER ALL
GO



ALTER TABLE [ManagerAssignments] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [ManagerAssignments] DISABLE TRIGGER ALL
GO

PRINT 'Begin inserting data in ManagerAssignments'
ALTER TABLE [ManagerAssignments] CHECK CONSTRAINT ALL
GO

ALTER TABLE [ManagerAssignments] ENABLE TRIGGER ALL
GO



ALTER TABLE [ProjectAssignments] NOCHECK CONSTRAINT ALL
GO
ALTER TABLE [ProjectAssignments] DISABLE TRIGGER ALL
GO

PRINT 'Begin inserting data in ProjectAssignments'
ALTER TABLE [ProjectAssignments] CHECK CONSTRAINT ALL
GO

ALTER TABLE [ProjectAssignments] ENABLE TRIGGER ALL
GO



